pr: none
trigger: none

jobs:

  - job: Linux
    pool:
      vmImage: 'ubuntu-latest'

    strategy:
      matrix:
        ubuntu2004:
          image: symless/synergy-core:ubuntu20.04
          packager: deb
          name: ubuntu20

    container: $[ variables['image'] ]

    steps:
      - template: CI/checkout.yml
      - template: CI/Linux/linux-build.yml

  - job: MacOS
    strategy:
      matrix:
        catalina-std:
          image: macOS-10.15
          platform: x86-64
          version: 10.14
          buildType: "standard"
          prefix: "synergy"

    pool:
      vmImage: $[ variables['image'] ]

    variables:
      QT_VERSION: '5.15.2'
      QT_PATH: '/usr/local/opt/qt'
      Qt5_DIR: '$(QT_PATH)/$(QT_VERSION)/clang_64'

    steps:
      - template: CI/checkout.yml
      - template: CI/MacOS/mac-build.yml

  - job: Windows
    strategy:
      matrix:
        vs2019:
          image: windows-2019
          buildType: "standard"
          prefix: "synergy"

    pool:
      vmImage: $[ variables['image'] ]

    variables:
      QT_VERSION: '5.12.6'
      QLI_OUT_DIR: '.\deps\Qt'
      QLI_BASE_URL: 'http://qt.mirror.constant.com/'
      QT_BIN_PATH: '$(Build.Repository.LocalPath)\$(QLI_OUT_DIR)\$(QT_VERSION)\msvc2017_64'
      QT_BIN_PATH_32: '$(Build.Repository.LocalPath)\$(QLI_OUT_DIR)\$(QT_VERSION)\msvc2017'
      BONJOUR_SDK_DIR: 'deps\BonjourSDK'
      ENV_BAT: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\Tools\vsdevcmd'

    steps:
      - template: CI/checkout.yml
      - template: CI/Windows/windows-build.yml
